version: "3"
services:
  api:
    image: mdillon/postgis:11-alpine
    container_name: "gobarber_api"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gobarber_dev
      TZ: GMT
    ports:
      - 5432:5432
  mongobarber:
    image: mongo
    ports:
      - 27017:27017
